# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-11 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xenos_admin', '0002_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='profit',
            field=models.IntegerField(default=0),
        ),
    ]
