# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-11 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xenos_admin', '0003_auto_20180211_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Percentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.CharField(max_length=20)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xenos_admin.Plan')),
            ],
        ),
        migrations.AlterField(
            model_name='investment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
