# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-11 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xenos_admin', '0004_auto_20180211_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='percentage',
            name='percentage',
            field=models.DecimalField(decimal_places=3, max_digits=19, max_length=20),
        ),
    ]
