# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-11 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xenos_admin', '0006_investment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
