# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-11 18:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xenos_admin', '0007_investment_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 11, 19, 56, 31, 501000), null=True),
        ),
    ]
