# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-14 04:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xenos_admin', '0008_auto_20180211_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 14, 5, 14, 1, 319000), null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[(b'Pending', b'Pending'), (b'Active', b'Active'), (b'Completed', b'Completed')], default=b'Pending', max_length=200, null=True),
        ),
    ]
