# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-14 04:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xenos_admin', '0009_auto_20180214_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='bitaddress',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='reinvest',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 14, 5, 26, 32, 265000), null=True),
        ),
    ]
