# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-17 03:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xenos_admin', '0011_auto_20180216_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='btc_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 17, 4, 13, 46, 1000), null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='profit',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='percentage',
            name='percentage',
            field=models.DecimalField(decimal_places=10, max_digits=19, max_length=20),
        ),
    ]
