# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-17 03:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xenos_admin', '0012_auto_20180217_0413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_type', models.CharField(choices=[(b'Credit', b'Credit'), (b'Withdrawal', b'Withdrwal')], max_length=200)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[(b'Pending', b'Pending'), (b'Success', b'Success')], max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='investment',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 17, 4, 47, 58, 745000), null=True),
        ),
    ]
