# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-17 05:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xenos_admin', '0015_auto_20180217_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='referer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 17, 6, 6, 20, 688000), null=True),
        ),
    ]
