# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-17 05:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xenos_admin', '0016_auto_20180217_0606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='referer',
        ),
        migrations.AlterField(
            model_name='investment',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 17, 6, 13, 33, 679000), null=True),
        ),
    ]
