# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-17 05:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xenos_admin', '0017_auto_20180217_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 17, 6, 20, 26, 692000), null=True),
        ),
    ]
