# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-17 05:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xenos_admin', '0018_auto_20180217_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='info',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 17, 6, 42, 18, 237000), null=True),
        ),
    ]
