# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-17 10:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xenos_admin', '0019_auto_20180217_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justin', models.CharField(max_length=20)),
                ('data', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='investment',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 17, 11, 51, 4, 146000), null=True),
        ),
    ]
