# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-22 13:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xenos_admin', '0024_auto_20180222_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='xenos_payment',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 22, 14, 41, 57, 447000), null=True),
        ),
    ]
