# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-22 17:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xenos_admin', '0026_auto_20180222_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 22, 18, 51, 53, 313000), null=True),
        ),
    ]
