# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-01 04:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xenos_admin', '0027_auto_20180222_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 1, 5, 49, 21, 220199), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success')], max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trans_type',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Withdrawal', 'Withdrwal')], max_length=200),
        ),
        migrations.AlterField(
            model_name='xenos_payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success')], max_length=200, null=True),
        ),
    ]
