# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-01 05:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xenos_admin', '0028_auto_20180301_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 1, 6, 45, 6, 602307), null=True),
        ),
    ]
