# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-05 11:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xenos_admin', '0029_auto_20180301_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='model_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='model_trans',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 5, 12, 45, 40, 193000), null=True),
        ),
    ]
