# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-05 14:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xenos_admin', '0030_auto_20180405_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bitaddress',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 5, 15, 12, 54, 726000), null=True),
        ),
    ]
