# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-05 14:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xenos_admin', '0031_auto_20180405_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 5, 15, 19, 14, 185000), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='bitaddress',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
