# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-06 14:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xenos_admin', '0033_auto_20180406_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 6, 15, 17, 10, 965000), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=50),
        ),
    ]
