# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-11 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='wallet',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
