# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-16 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0002_auto_20180211_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='passport',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
