# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-17 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0005_auto_20180217_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_image',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
