# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-22 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0006_profile_id_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='passpost',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
