# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-01 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0008_remove_profile_passpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
